controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - prbt_joint_1
      - prbt_joint_2
      - prbt_joint_3
      - prbt_joint_4
      - prbt_joint_5
      - prbt_joint_6
initial:  # Define initial robot poses per group
#  - group: arm
#    pose: home

  []