version: '3'

services:
    calibration:
        build:
            context: .
        image: melodic-calibration
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities:
                            - gpu
        stdin_open: true
        tty: true
        privileged: true
        network_mode: "host"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - /dev/shm:/dev/shm
            - /dev/*:/dev/*
            - ../../src:/home/admin/catkin_ws/src
        environment:
            - DISPLAY=$DISPLAY
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        entrypoint: /usr/local/bin/scripts/workspace-entrypoint.sh
        command: tail -f /dev/null # bash -c "top"
