<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_cell">
    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:macro name="robot_cell" params="
        name
        prefix
        parent
        *origin">
        <xacro:property name="robot_center_offset_length" value="0.315" />
        <xacro:property name="robot_center_offset_width" value="0.02" />
        <xacro:property name="robot_base_height" value="0.62" />
        <xacro:property name="robotcell_length" value="1.20" />
        <xacro:property name="robotcell_width" value="0.80" />
        <xacro:property name="robotcell_height" value="1.16" />
        <xacro:property name="shield_thickness" value="0.045" />

        <material name="gray">
            <color rgba="0.6 0.8 0.8 1" />
        </material>

        <link name="${prefix}visuals_link">
            <visual>
                <geometry>
                    <mesh filename="package://prbt_cell_description/meshes/prbt_cell_v1.0.STL" scale="0.001 0.001 0.001" />
                </geometry>
                <material name="gray"/>
            </visual>
        </link>
        <link name="${prefix}shield_front_link">
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <geometry>
                    <box size="${robotcell_length} ${shield_thickness} ${robotcell_height}" />
                </geometry>
                <material name="gray"/>
            </collision>
            <xacro:inertial_box mass="5" x="${robotcell_length}" y="${shield_thickness}" z="${robotcell_height}">
                <origin rpy="0 0 0" xyz="0 0 0" />
            </xacro:inertial_box>
        </link>

        <link name="${prefix}shield_rear_link">
            <collision>
                <origin rpy="0 0 0 " xyz="0 0 0" />
                <geometry>
                    <box size="${robotcell_length} ${shield_thickness*2} ${robotcell_height}" />
                </geometry>
                <material name="gray"/>
            </collision>
            <xacro:inertial_box mass="5" x="${robotcell_length}" y="${shield_thickness*2}" z="${robotcell_height}">
                <origin rpy="0 0 0" xyz="0 0 0" />
            </xacro:inertial_box>
        </link>

        <link name="${prefix}shield_right_link">
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <geometry>
                    <box size="${shield_thickness} ${robotcell_width} ${robotcell_height}" />
                </geometry>
                <material name="gray"/>
            </collision>
            <xacro:inertial_box mass="5" x="${shield_thickness}" y="${robotcell_width}" z="${robotcell_height}">
                <origin rpy="0 0 0" xyz="0 0 0" />
            </xacro:inertial_box>
        </link>

        <link name="${prefix}shield_left_link">
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <geometry>
                    <box size="${shield_thickness} ${robotcell_width} ${robotcell_height}" />
                </geometry>
                <material name="gray"/>
            </collision>
            <xacro:inertial_box mass="5" x="${shield_thickness}" y="${robotcell_width}" z="${robotcell_height}">
                <origin rpy="0 0 0" xyz="0 0 0" />
            </xacro:inertial_box>
        </link>

        <link name="${prefix}robotcell_base_link">
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${robot_base_height/2}" />
                <geometry>
                    <box size="${robotcell_length} ${robotcell_width} ${robot_base_height}" />
                </geometry>
                <material name="gray"/>
            </collision>
            <xacro:inertial_box mass="70" x="${robotcell_length}" y="${robotcell_width}" z="${robot_base_height}">
                <origin rpy="0 0 0" xyz="0 0 0" />
            </xacro:inertial_box>
        </link>
        <link name="${prefix}robotcell_collision_base_link">
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${robot_base_height/2}" />
                <geometry>
                    <box size="${robotcell_length} ${robotcell_width} ${robot_base_height+0.12}" />
                </geometry>
                <material name="gray"/>
            </collision>
            <xacro:inertial_box mass="70" x="${robotcell_length}" y="${robotcell_width}" z="${robot_base_height+0.12}">
                <origin rpy="0 0 0" xyz="0 0 0" />
            </xacro:inertial_box>
        </link>
        <link name="${prefix}robot_link" />

        <joint name="${prefix}robotcell_base_to_visual" type="fixed">
            <parent link="${prefix}robotcell_base_link" />
            <child link="${prefix}visuals_link" />
            <origin xyz="${robotcell_length/2} -${robotcell_width/2} 0" rpy="0 0 ${pi/2}" />
        </joint>
        <joint name="${prefix}robotcell_base_to_front_joint" type="fixed">
            <parent link="${prefix}robotcell_base_link" />
            <child link="${prefix}shield_front_link" />
            <origin xyz="0 ${robotcell_width/2-shield_thickness/2} ${robot_base_height+robotcell_height/2}" rpy="0 0 0" />
        </joint>

        <joint name="${prefix}robotcell_base_to_rear" type="fixed">
            <parent link="${prefix}robotcell_base_link" />
            <child link="${prefix}shield_rear_link" />
            <origin xyz="0 ${-robotcell_width/2+shield_thickness} ${robot_base_height+robotcell_height/2}" rpy="0 0 0" />
        </joint>

        <joint name="${prefix}robotcell_base_to_left" type="fixed">
            <parent link="${prefix}robotcell_base_link" />
            <child link="${prefix}shield_left_link" />
            <origin xyz="${-robotcell_length/2+shield_thickness/2} 0 ${robot_base_height+robotcell_height/2}" rpy="0 0 0" />
        </joint>

        <joint name="${prefix}robotcell_base_to_right" type="fixed">
            <parent link="${prefix}robotcell_base_link" />
            <child link="${prefix}shield_right_link" />
            <origin xyz="${robotcell_length/2-shield_thickness/2} 0 ${robot_base_height+robotcell_height/2}" rpy="0 0 0" />
        </joint>
        <joint name="${prefix}robot_cell_base_joint" type="fixed">
            <parent link="${parent}" />
            <child link="${prefix}robotcell_base_link" />
            <xacro:insert_block name="origin" />
        </joint>
        <joint name="${prefix}robot_cell_collision_base_joint" type="fixed">
            <parent link="${parent}" />
            <child link="${prefix}robotcell_collision_base_link" />
            <xacro:insert_block name="origin" />
        </joint>
        <joint name="${prefix}robot_cell_base_to_robot_link" type="fixed">
            <parent link="${prefix}robotcell_base_link" />
            <child link="${prefix}robot_link" />
            <origin xyz="${robot_center_offset_length} ${robot_center_offset_width} ${robot_base_height}" rpy="0 0 0" />
        </joint>
    </xacro:macro>
</robot>
