name: ROS2 Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  ci_build:
    name: Colcon Build
    needs: deploy_documentation
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: colcon_ws

    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/${{ env.BUILD_DIR }}/src
      - name: My Action
        id: ros2
        uses: prachandabhanu/ros2-github-action@main
        with:
          image:  prachandabhanu/build_env:ros2-humble-kuka
          options: -v ${{ github.workspace }}/${{ env.BUILD_DIR }}/src:/${{ env.BUILD_DIR }}/src
          run: |
            cd /${{ env.BUILD_DIR }}/src
            echo "cd inside colcon workspace src"
            ls -a
            cd /${{ env.BUILD_DIR }}
            echo "cd inside colcon workspace"
            ls -a
            source /opt/ros/humble/setup.bash
            echo "Now colcon build"
            colcon build --symlink-install
            echo "Finished to build"
